"""
STATE.PY — The single most important file in a LangGraph application.

WHY DO WE NEED THIS?
Every node in the graph needs to communicate with every other node.
Instead of passing data manually between functions, LangGraph uses a
shared "state" object — like a whiteboard that every node can read and write.

HOW IT WORKS:
- Every node receives the FULL current state
- Every node returns a PARTIAL update (only the keys it changed)
- LangGraph merges updates automatically using "reducers"

THE SPECIAL PART — add_messages:
For normal keys (str, int, list), the new value REPLACES the old one.
For `messages`, we use `add_messages` reducer — it APPENDS new messages
instead of replacing the list. This is how chat history builds up.
"""

from typing import List
from typing_extensions import TypedDict, Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    # ── CONVERSATION HISTORY ──────────────────────────────────────────────
    # Annotated[list, add_messages] means:
    # - It's a list of BaseMessage objects (HumanMessage, AIMessage, etc.)
    # - add_messages reducer APPENDS new messages instead of replacing the list
    # - This is what makes multi-turn conversation work automatically
    messages: Annotated[List[BaseMessage], add_messages]

    # ── CURRENT TURN DATA ─────────────────────────────────────────────────
    # The current user's question extracted from messages
    query: str

    # What kind of question is this? Used for routing.
    # Possible values: "greeting" | "math" | "rag" | "general"
    query_type: str

    # ── RAG DATA ──────────────────────────────────────────────────────────
    # Document chunks retrieved from the vector store
    # Each item is a string (the text content of one chunk)
    documents: List[str]

    # How many times have we retried retrieval with a rewritten query?
    # We use this to prevent infinite loops: max 2 retries then give up
    retry_count: int

    # ── FINAL OUTPUT ──────────────────────────────────────────────────────
    # The final answer generated by the LLM
    generation: str
